url = "https://cdn.modrinth.com/data/EsAfCjCV/versions/VfjnbBAT/appleskin-fabric-mc1.21.5-3.0.6.jar"
name = "appleskin"
file_name = "appleskin-fabric-mc1.21.5-3.0.6.jar"
hash = "1czgysmb22k7cxj1b51k33m94vqi9ggrh6bhjpi8gy04j8rh7zp6"
depends = ["fabricapi"]
tags = ["food", "utility"]
apipkgid = "EsAfCjCV"
apiverid = "VfjnbBAT"
