url = "https://cdn.modrinth.com/data/P7dR8mSH/versions/YozemL2T/fabric-api-0.127.0%2B1.21.5.jar"
name = "fabricapi"
file_name = "fabric-api-0.127.0+1.21.5.jar"
hash = "0zljwpcnzkdifmi14n2yvc8pvxjykd8qcyhalbcadqncxqfnywcb"
tags = ["library"]
apipkgid = "P7dR8mSH"
apiverid = "YozemL2T"
