url = "https://cdn.modrinth.com/data/AANobbMI/versions/fVbw1C7i/sodium-fabric-0.6.12%2Bmc1.21.5.jar"
name = "sodium"
file_name = "sodium-fabric-0.6.12+mc1.21.5.jar"
hash = "1007ay6kfxbl1j4i7b21nqbl8cbi6m9bc8bscxmsj1h5v60kgad4"
tags = ["optimization"]
apipkgid = "AANobbMI"
apiverid = "fVbw1C7i"
